language: java
sudo: required
dist: bionic

jdk:
  - openjdk10

before_install:
  - sudo apt-get install ant
  - zip -r fox.jason.unit-test.zip . -x *.zip* *.git/* *temp/* *out/*
  - curl -LO https://github.com/dita-ot/dita-ot/releases/download/$DITA_OT/dita-ot-$DITA_OT.zip
  - unzip -q dita-ot-$DITA_OT.zip
  - chmod +x dita-ot-$DITA_OT/bin/dita

install:
  - dita-ot-$DITA_OT/bin/dita --install https://github.com/jason-fox/com.here.validate.svrl/archive/v2.0.2.zip
  - dita-ot-$DITA_OT/bin/dita --install https://github.com/jason-fox/com.here.validate.svrl.text-rules/archive/v2.0.2.zip
  - dita-ot-$DITA_OT/bin/dita --install fox.jason.unit-test.zip
  

script:
  - dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/fox.jason.unit-test -f unit-test --output . -v

jobs:
  include:
    - stage: test
      name: "Unit Tests: DITA_OT=3.3.4"
      env: DITA_OT=3.3.4

      before_script:
        - dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/fox.jason.unit-test -f xsl-instrument

      after_success:
        - cp dita-ot-$DITA_OT/plugins/fox.jason.unit-test/resource/pom.xml pom.xml
        - mvn clean org.eluder.coveralls:coveralls-maven-plugin:report

    - stage: test
      name: "Unit Tests: DITA_OT=2.5.4"
      env: DITA_OT=2.5.4
