language: java
jdk:
  - oraclejdk8
env:
  - DITA_OT=2.5.4
  - DITA_OT=3.3
before_script:
  - zip -r fox.jason.unit-test.zip . -x *.zip* *.git/* *temp/* *out/*
  - curl -LO https://github.com/dita-ot/dita-ot/releases/download/$DITA_OT/dita-ot-$DITA_OT.zip
  - unzip -q dita-ot-$DITA_OT.zip
  - chmod +x dita-ot-$DITA_OT/bin/dita
  - dita-ot-$DITA_OT/bin/dita --install https://github.com/jason-fox/com.here.validate.svrl/archive/master.zip
  - dita-ot-$DITA_OT/bin/dita --install https://github.com/jason-fox/com.here.validate.svrl.text-rules/archive/master.zip
  - dita-ot-$DITA_OT/bin/dita --install fox.jason.unit-test.zip
  - dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/fox.jason.unit-test -f xsl-instrument 
script:
  - dita-ot-$DITA_OT/bin/dita --input dita-ot-$DITA_OT/plugins/fox.jason.unit-test -f unit-test --output . -v
after_success:
  - cp dita-ot-$DITA_OT/plugins/fox.jason.unit-test/resource/pom.xml pom.xml
  - mvn clean org.eluder.coveralls:coveralls-maven-plugin:report 