site_name: Unit Test Framework Plug-in

repo_url: https://github.com/jason-fox/fox.jason.unit-test
repo_name: GitHub

pages:
    -  Home: index.md
    - 'Install' : 'install.md'
    - 'Usage' : 'usage.md'
    - 'Unit Test File Structure' : 'unit-test-file-structure.md'
    - 'Unit Testing ANT Tasks' : 'api.md'

theme: readthedocs
extra_css: ["https://jason-fox.github.io/fox.jason.unit-test/dita.css"]