site_name: Unit Test Framework for DITA-OT

repo_url: https://github.com/jason-fox/fox.jason.unit-test
repo_name: GitHub

pages:
    -  Home: index.md
    - 'Install' : 'install.md'
    - 'Usage' : 'usage.md'
    - 'Unit Test File Structure' : 'unit-test-file-structure.md'
    - 'Unit Testing ANT Tasks' : 'api.md'

theme: readthedocs